//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int BeerID { get; set; }
        public int BeerStyleID { get; set; }
        public string BeerName { get; set; }
        public short ABVID { get; set; }
        public System.DateTime DateSold { get; set; }
        public int EmployeeID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public int DirectReportID { get; set; }
        public int PkgID { get; set; }
    
        public virtual BeerStyle BeerStyle { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Package Package { get; set; }
        public virtual Status Status { get; set; }
    }
}
